version: '3.8'

services:
  postgres-db:
    image: postgres:14
    container_name: contact_postgres_db
    environment:
      POSTGRES_DB: contact_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpass123
    command: -c password_encryption=md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  contact-backend:
    build: ./contact-book-backend
    container_name: contact_backend_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/contact_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: testpass123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: unless-stopped

  contact-frontend:
    build:
      context: ./contact-book-frontend
      dockerfile: Dockerfile
    container_name: contact_frontend_app
    ports:
      - "3000:80"
    depends_on:
      - contact-backend
    restart: unless-stopped
    environment:
     VITE_REACT_APP_API_BASE_URL: http://contact-backend:8080

volumes:
  postgres_data:
