CREATE TABLE contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-incrementing primary key
    first_name VARCHAR(255) NOT NULL,                       -- First name (required)
    last_name VARCHAR(255) NOT NULL,                        -- Last name (required)
    email VARCHAR(255) NOT NULL UNIQUE,                     -- Email (required and unique)
    phone_number VARCHAR(50)                          -- Phone number (optional)
);
